/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "app.h"

wyjscie *
obliczenia_1_svc(wejscie *argp, struct svc_req *rqstp)
{
	static wyjscie result;
	for (int i = 0; i < argp->size; ++i)
	{
		printf("%02X ", argp->x1[i]);
	}
	fflush(stdout);

	return &result;
}
